apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xdc32asjx-go 
  janus-idp.io/tekton: xdc32asjx-go
  backstage.io/kubernetes-id: xdc32asjx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xdc32asjx-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml